// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD6ORHTE7642r0ZYOjO0LOEGCif_pn7sY',
    appId: '1:900832659641:web:88f541171b8f3598b37368',
    messagingSenderId: '900832659641',
    projectId: 'author-registration-app-5219f',
    authDomain: 'author-registration-app-5219f.firebaseapp.com',
    storageBucket: 'author-registration-app-5219f.appspot.com',
    measurementId: 'G-H4B3XNT2SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJ4taFP2zGfR9gnJVo6G4x_F9e9W7PXg',
    appId: '1:900832659641:android:161b2ac71bb69bc5b37368',
    messagingSenderId: '900832659641',
    projectId: 'author-registration-app-5219f',
    storageBucket: 'author-registration-app-5219f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kEvxzLKV4EYYOb82Oug6Zs5qMW9gqe0',
    appId: '1:900832659641:ios:66edd18247fe7f59b37368',
    messagingSenderId: '900832659641',
    projectId: 'author-registration-app-5219f',
    storageBucket: 'author-registration-app-5219f.appspot.com',
    iosClientId: '900832659641-mf237c614t38mku1l39abst4nus461mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kEvxzLKV4EYYOb82Oug6Zs5qMW9gqe0',
    appId: '1:900832659641:ios:66edd18247fe7f59b37368',
    messagingSenderId: '900832659641',
    projectId: 'author-registration-app-5219f',
    storageBucket: 'author-registration-app-5219f.appspot.com',
    iosClientId: '900832659641-mf237c614t38mku1l39abst4nus461mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authorApp',
  );
}
